"""Common edsm fields and values."""

# Tkinter event callback
EDSM_CALLBACK_SEQUENCE = '<<EDSMCallback>>'

# Logging
LOG_CRIT = 1
LOG_ERROR = 2
LOG_WARN = 3
LOG_INFO = 4
LOG_DEBUG = 5

LOG_OUTPUT = {
    1: "CRITICAL",
    2: "ERROR",
    3: "WARNING",
    4: "INFO",
    5: "DEBUG",
    0: "UNKNOWN",
}

JOURNAL_ENTRY_FIELD_NAME = "Name"
JOURNAL_ENTRY_FIELD_PERCENT = "Percent"
JOURNAL_ENTRY_FIELD_EVENT = "event"
JOURNAL_ENTRY_FIELD_STAR_SYSTEM = "StarSystem"
JOURNAL_ENTRY_FIELD_SYSTEM_ADDRESS = "SystemAddress"
JOURNAL_ENTRY_FIELD_SCAN_TYPE = "ScanType"
JOURNAL_ENTRY_FIELD_BODY_NAME = "BodyName"
JOURNAL_ENTRY_FIELD_BODY_COUNT = "BodyCount"
JOURNAL_ENTRY_FIELD_LANDABLE = "Landable"
JOURNAL_ENTRY_FIELD_MATERIALS = "Materials"

JOURNAL_ENTRY_VALUE_EVENT_FSS_DISCOVERY_SCAN = "FSSDiscoveryScan"
JOURNAL_ENTRY_VALUE_EVENT_FSDJUMP = "FSDJump"
JOURNAL_ENTRY_VALUE_EVENT_SCAN = "Scan"

JOURNAL_ENTRY_VALUE_SCAN_TYPE_DETAILED = "Detailed"
JOURNAL_ENTRY_VALUE_SCAN_TYPE_AUTOSCAN = "AutoScan"

EDSM_RESPONSE_FIELD_BODIES = 'bodies'
EDSM_RESPONSE_FIELD_BODY_COUNT = 'bodyCount'
EDSM_RESPONSE_FIELD_ID = 'id'
EDSM_RESPONSE_FIELD_ID64 = 'id64'
EDSM_RESPONSE_FIELD_NAME = 'name'
EDSM_RESPONSE_FIELD_URL = 'url'
